language: java
jdk: oraclejdk8
install: "pip install -r requirements.txt"
script: "./gradlew check"
sudo: true
after_success:
- "./gradlew jacocoRootReport coveralls"
- "./release-site.sh"
- "travis_wait 120 ./release-ci.sh"
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
