language: java
jdk:
- oraclejdk8
script:
- "./gradlew check"
after_success:
- "./gradlew cobertura coveralls"
- "./release-ci.sh"
ache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"

notifications:
  slack: contractorscum:DiikH6t3ig2ZKfVMP1SQ9peR
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
