matrix:
  include:
    - stage: build
      language: java
      jdk: oraclejdk8
      script:
      - "./gradlew check"
      after_success:
      - "./gradlew jacocoRootReport coveralls"
      cache:
        directories:
        - "$HOME/.m2"
        - "$HOME/.gradle"
    - stage: bintray
      language: bash
      script: "./release-ci.sh"
    - stage: maven central
      script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-aws
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-core
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-contract
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-template-handlebars
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-template-pebble
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-template-thymeleaf
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-client-apache
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-client-okhttp
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-format-argo
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-format-gson
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-format-jackson
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-server-jetty
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-server-netty
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-server-undertow
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-testing-hamkrest
    - script: "./release-maven-central-single.sh"
      language: bash
      env: PACKAGE_NAME=http4k-testing-webdriver
    - stage: docs
      language: python
      script:
        - "./release-site.sh"
