language: java
jdk: oraclejdk8
install:
- "pip install virtualenv"
- "virtualenv ./virtualenv"
- "source ./virtualenv/bin/activate"
script: "./gradlew check"
after_success:
- "./gradlew jacocoRootReport coveralls"
- "./release-site.sh"
- "travis_wait 120 ./release-ci.sh"
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
