matrix:
  include:
    - stage: build
      language: java
      jdk: oraclejdk8
      script:
      - "./gradlew check"
      after_success:
      - "./gradlew jacocoRootReport coveralls"
      cache:
        directories:
        - "$HOME/.m2"
        - "$HOME/.gradle"
    - stage: bintray
      language: bash
      script: "./release-ci.sh"
    - stage: docs
      language: python
      script:
      - "./release-site.sh"
    - stage: maven central
      script: "travis_wait 60 ./release-maven-central.sh"
      language: bash