language: java
jdk:
- oraclejdk8
script:
- "./gradlew check"
after_success:
- "./gradlew cobertura coveralls"
- "travis_wait 30 ./release-ci.sh"
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"

notifications:
  slack:
    rooms: contractorscum:DiikH6t3ig2ZKfVMP1SQ9peR
    template:
          - "%{repository} (%{commit}) : %{commit_message}. Build details: %{build_url}"