env:
 - PACKAGE_NAME=http4k-aws
 - PACKAGE_NAME=http4k-core
 - PACKAGE_NAME=http4k-contract
 - PACKAGE_NAME=http4k-template-handlebars
 - PACKAGE_NAME=http4k-template-pebble
 - PACKAGE_NAME=http4k-template-thymeleaf
 - PACKAGE_NAME=http4k-client-apache
 - PACKAGE_NAME=http4k-client-okhttp
 - PACKAGE_NAME=http4k-format-argo
 - PACKAGE_NAME=http4k-format-gson
 - PACKAGE_NAME=http4k-format-jackson
 - PACKAGE_NAME=http4k-server-jetty
 - PACKAGE_NAME=http4k-server-netty
 - PACKAGE_NAME=http4k-server-undertow
 - PACKAGE_NAME=http4k-testing-hamkrest
 - PACKAGE_NAME=http4k-testing-webdriver

jobs:
  include:
    - stage: build
      language: java
      jdk: oraclejdk8
      script:
      - "./gradlew clean"
      after_success:
      - "./gradlew clean"
      cache:
        directories:
        - "$HOME/.m2"
        - "$HOME/.gradle"
    - stage: bintray
      language: bash
      script: "./release-ci.sh"
    - stage: maven central
      language: bash
      script: "./release-maven-central-single.sh"
      env: PACKAGE_NAME=http4k-aws
    - stage: docs
      language: python
      script:
        - "./release-site.sh"
