language: java
jdk:
- oraclejdk8
script:
- "./gradlew check"
after_success:
- "./gradlew cobertura coveralls"
- "./release-ci.sh"
ache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: mzzBQqNstr+ia2GjaQEGc4F3C/xWueNRn92oxeJ5gy1MOKG9tROIIP7XrnDjw+xB8MbJpJO1GbC/h40JZi2t718+6F13sxE387Nrr2Aa59eCUI+fVIWjJPo02M6G0k7rHRHMslkTC8cS59hT3L1C7oalQpfa1Owe54pJzTxAptC8DYcmU7sn787apfSZuxzF+Vihpglcd6fEXSmTk2vMd7H5BrfEVwi+HzSe1BwVi3ZRSkb9lJhGVQ3kZUr4+mUqrLTOJe9M1ryBGbBrRWXD4tOkZ/JbJiWh6tNNVAVL+73a92vzVH8tgNXdMHcDlUAHstwC7g/bzvQ4kn64X1GEggjEVVoTxMgxUfz+Lcv81LQCRxiBEK5EYlYVTJjD5oTVgM8yFqcb2JHFZquG7vG4fyKpjew7wnDIoPmwMIRRvjBfZZAPvNF7Z6U/StNSvDXFuHa5+LnMXru48IUKjgtTg03PMfaCg2adMGOxdHIOxVkzm1IZQkqBdzDES3Cyr6WPl2kKNNxtH+I38fOt6ClhWNe28Y4Sd+k7Y0fP6GMy/4fCA3svlqtpbLx7kLcmjXiObK8LILq259ih+yBWW3pFHqZQ42gKiBAJVq9Qeqqrdp6EVYhhoWzAHwCZg1BDMe/RzM/H1z9slWaFkrsm+FA2+ynegJ/08SAWppKS+qruSjs=
  - secure: CuOw/P5kDiuNPc/IXvgwd6QhVgsW1yvRM3NIqFCi7DII3ZfrH6YBM7/PEWBQoJgBZ8SZopIZD7IAQ8M6WmYjezuKvMJFvsy9KwItsRgJwv8WMZH0dHsF29UIRRssWwjMln6ah6lv0+Kdrry3mAFqO7D05z+UFEb+8cU+m6PsxHdr3iSJK2NaTNxgtkHP7bFGJVoY8JRRLBYbsCUjWwYE+b2DEC2MH44+ck3bJNq2DPRtC4aPdqmOsZLoGOXwXaytfWZumsTB5dSwrw6E+NBnXUidM2aSkJjDcoWoJQhmigl4sMRgH+cmC59EHXV3Nz41pS6uhxAEXQxGFQ8d4cbf9mxxt2pA8h0F7N9qLABLBFpF+bQb3DjdoH4YcWZIrrZZebBkOiWx/db8oHMRRivDO9jq2sHzZOZalB8+Rmml0RYibNEkBOv70KKgzDA48k4sFbquttpS6zZIwImGTQuhTPkyvVaxVABXxNj7TIbWPtkRBL8lyv26v0TGFp9KNrptbnw6rTKbIKhw4+MfbSjMdG3SeNy6EmzUk9NBQzfuMxAC5/jtx1KAE+uzKe/7QgxR9r1XKFBrF+rPyPwLPT4hmthsxxx8udC9tmFwluUjDYpiuFy5Ox8pAckbo5ANJ7yN+NyIsP1nOr3SNoB7xqmAUIdymfpbw33MQTlRQw8aMHM=
