language: java
jdk:
- oraclejdk8
script:
- "./gradlew check"
after_success:
- "./gradlew cobertura coveralls"
- "travis_wait 30 ./release-ci.sh"
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
