site_name: http4k
site_url: http://www.http4k.org
site_description: Http4k documentation
site_author: David Denton (@daviddenton), IvanSanchez (@s4nchez)
remote_branch: master
repo_url: https://github.com/http4k/http4k/
theme: 'material'
theme_dir: ./docs/theme
markdown_extensions:
  - meta
  - codehilite
extra_css:
  - ./css/site.css
extra:
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue.png

pages:
  - Introduction: index.md
  - Rationale & Concepts: rationale.md
  - Installation:  installation.md
  - Getting started: quickstart.md
  - Developer Guide:
    - Modules:
      - Core: guide/modules/core.md
      - Server Backend: guide/modules/servers.md
      - HTTP Client: guide/modules/clients.md
      - Message Formats: guide/modules/message_formats.md
      - Templating: guide/modules/templating.md
      - Typesafe Contracts: guide/modules/contracts.md
    - Application Testing: guide/testing.md
    - Worked TDD Example:
      - Introduction: guide/example/index.md
      - Building a walking skeleton: guide/example/building-a-walking-skeleton.md
      - Adding an endpoint: guide/example/adding-the-first-endpoint.md
      - Adding another endpoint: guide/example/adding-the-second-endpoint.md
      - An external dependency: guide/example/adding-an-external-dependency.md
  - Cookbook:
    - Recipe1: cookbook/recipe1.md
  - Performance: performance.md
  - HTTP4K in action: http4k-in-action.md
