site_name: http4k
site_url: http://www.http4k.org
site_description: Http4k documentation
site_author: David Denton (@daviddenton), IvanSanchez (@s4nchez)
remote_branch: master
repo_url: https://github.com/http4k/http4k/
theme: 'material'
theme_dir: ./docs/theme
extra_css:
  - ./css/site.css
extra:
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue.png