site_name: http4k
site_url: http://www.http4k.org
site_description: Http4k documentation
site_author: David Denton (@daviddenton), IvanSanchez (@s4nchez)
remote_branch: master
repo_url: https://github.com/http4k/http4k/
theme: 'material'
theme_dir: ./docs/theme
markdown_extensions:
  - meta
  - codehilite
extra_css:
  - ./css/site.css
extra:
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue.png

pages:
  - Introduction: index.md
  - Rationale & Concepts: rationale/index.md
  - Installation:  installation/index.md
  - Getting started: quickstart/index.md
  - Developer Guide:
    - Modules:
      - Core: guide/modules/core.md
      - Server Backend: guide/modules/servers.md
      - HTTP Client: guide/modules/clients.md
      - Message Formats: guide/modules/message_formats.md
      - Templating: guide/modules/templating.md
      - Typesafe Contracts: guide/modules/contracts.md
    - Application Testing: guide/testing.md
    - Worked TDD Example:
      - Introduction: guide/example/index.md
      - 1. Building a walking skeleton: guide/example/_1_building_a_walking_skeleton/index.md
      - 2. Adding an endpoint: guide/example/_2_adding_the_first_endpoint/index.md
      - 3. Adding another endpoint: guide/example/_3_adding_the_second_endpoint/index.md
      - 4. An external dependency: guide/example/_4_adding_an_external_dependency/index.md
  - Cookbook:
    - Server as a function: cookbook/server_as_a_function/index.md
  - Performance: performance/index.md
  - HTTP4K in action: in_action/index.md
