on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # required by release-tag.sh to correctly identify files changed in the last commit
          persist-credentials: false # required by release-tag.sh to allow pushing with another credentials so other workflows are triggered
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./build-ci.sh
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}@github.com/${GITHUB_REPOSITORY}.git
      - run: ./release-tag.sh
        if: github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}
