on:
  repository_dispatch:
    types: [http4k-release]
jobs:
  create-toolbox-release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger toolbox
        uses: peter-evans/repository-dispatch@v1.1.1
        with:
          token: ${{ secrets.TOOLBOX_REPO_TOKEN }}
          repository: http4k/toolbox
          event-type: http4k-release
          client-payload: '{"version": "${{ github.event.client_payload.version }}"}'
