on:
  push:
    tags:
      - 'test*'
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: http4k/toolbox
          token: ${{ secrets.TOOLBOX_TOKEN }}
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.tagName.outputs.tag }}
