on:
  push:
    branches:
      - 'master'
jobs:
  release-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6.7'
          architecture: 'x64'
      - name: Build Site
        run: echo '::set-env name=GH_TOKEN::${{ secrets.GITHUB_TOKEN }}' && ./release-site.sh
