on:
  push:
    branches:
      - 'master'
jobs:
  release-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 11
      #      - run: ./gradlew --no-daemon -i dokka
      - uses: actions/checkout@v2
        with:
          repository: http4k/api
          path: tmp
          token: ${{ secrets.AUTHOR_TOKEN }}
      - run: rm -rf tmp/*
      - run: cp -R build/ddoc/http4k/* tmp/
      - uses: EndBug/add-and-commit@v4
        with:
          cwd: 'tmp'
          message: 'release API docs'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTHOR_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: asdasd
          force: true
          directory: tmp
