on:
  repository_dispatch:
    types: [http4k-release]
jobs:
  slackify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./notify-slack.sh
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
