on:
  push:
    tags:
      - '*'
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "New version ${{ steps.tagName.outputs.tag }} 🎉. Changelog available at: https://github.com/http4k/http4k/releases"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
