on: [repository_dispatch]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  tweet:
    if: github.event.action == 'http4k-release'
    runs-on: ubuntu-latest
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "New version ${{ steps.tagName.outputs.tag }} 🎉. Changelog available at: https://github.com/http4k/http4k/releases"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
